toPaste = {
	[1] = {[1] = {["pos"] = {1,1},["block"] = "wetdirt",},[10] = {["pos"] = {1,10},["block"] = "cheapwallpaper",},},
	[2] = {[1] = {["pos"] = {2,1},["block"] = "cheapwallpaper",},[2] = {["pos"] = {2,2},["block"] = "wetdirt",},[3] = {["pos"] = {2,3},["block"] = "neonblock",},[4] = {["pos"] = {2,4},["block"] = "neonblock",},[5] = {["pos"] = {2,5},["block"] = "snow",},[6] = {["pos"] = {2,6},["block"] = "snow",},[7] = {["pos"] = {2,7},["block"] = "neonblock",},[8] = {["pos"] = {2,8},["block"] = "silverblock",},[9] = {["pos"] = {2,9},["block"] = "pressurisedbeam",},[10] = {["pos"] = {2,10},["block"] = "cheapwallpaper",},[11] = {["pos"] = {2,11},["block"] = "cheapwallpaper",},[12] = {["pos"] = {2,12},["block"] = "pressurisedbeam",},},
	[3] = {[1] = {["pos"] = {3,1},["block"] = "cheapwallpaper",},[2] = {["pos"] = {3,2},["block"] = "neonblock",},[3] = {["pos"] = {3,3},["block"] = "neonblock",},[4] = {["pos"] = {3,4},["block"] = "snow",},[5] = {["pos"] = {3,5},["block"] = "snow",},[6] = {["pos"] = {3,6},["block"] = "snow",},[7] = {["pos"] = {3,7},["block"] = "snow",},[8] = {["pos"] = {3,8},["block"] = "neonblock",},[9] = {["pos"] = {3,9},["block"] = "clay",},[10] = {["pos"] = {3,10},["block"] = "cheapwallpaper",},[11] = {["pos"] = {3,11},["block"] = "cheapwallpaper",},[12] = {["pos"] = {3,12},["block"] = "clay",},[13] = {["pos"] = {3,13},["block"] = "pressurisedbeam",},},
	[4] = {[1] = {["pos"] = {4,1},["block"] = "cheapwallpaper",},[2] = {["pos"] = {4,2},["block"] = "neonblock",},[3] = {["pos"] = {4,3},["block"] = "neonblock",},[4] = {["pos"] = {4,4},["block"] = "snow",},[5] = {["pos"] = {4,5},["block"] = "snow",},[6] = {["pos"] = {4,6},["block"] = "snow",},[7] = {["pos"] = {4,7},["block"] = "snow",},[8] = {["pos"] = {4,8},["block"] = "snow",},[9] = {["pos"] = {4,9},["block"] = "clay",},[10] = {["pos"] = {4,10},["block"] = "cheapwallpaper",},[11] = {["pos"] = {4,11},["block"] = "wetdirt",},[12] = {["pos"] = {4,12},["block"] = "clay",},[13] = {["pos"] = {4,13},["block"] = "clay",},},
	[5] = {[2] = {["pos"] = {5,2},["block"] = "neonblock",},[3] = {["pos"] = {5,3},["block"] = "neonblock",},[4] = {["pos"] = {5,4},["block"] = "neonblock",},[5] = {["pos"] = {5,5},["block"] = "snow",},[6] = {["pos"] = {5,6},["block"] = "snow",},[7] = {["pos"] = {5,7},["block"] = "snow",},[8] = {["pos"] = {5,8},["block"] = "neonblock",},[9] = {["pos"] = {5,9},["block"] = "clay",},[10] = {["pos"] = {5,10},["block"] = "clay",},[11] = {["pos"] = {5,11},["block"] = "clay",},[12] = {["pos"] = {5,12},["block"] = "clay",},[13] = {["pos"] = {5,13},["block"] = "clay",},},
	[6] = {[1] = {["pos"] = {6,1},["block"] = "wetdirt",},[2] = {["pos"] = {6,2},["block"] = "clay",},[3] = {["pos"] = {6,3},["block"] = "silverblock",},[4] = {["pos"] = {6,4},["block"] = "neonblock",},[5] = {["pos"] = {6,5},["block"] = "neonblock",},[6] = {["pos"] = {6,6},["block"] = "neonblock",},[7] = {["pos"] = {6,7},["block"] = "neonblock",},[8] = {["pos"] = {6,8},["block"] = "silverblock",},[9] = {["pos"] = {6,9},["block"] = "clay",},[10] = {["pos"] = {6,10},["block"] = "clay",},[11] = {["pos"] = {6,11},["block"] = "neonblock",},[12] = {["pos"] = {6,12},["block"] = "clay",},[13] = {["pos"] = {6,13},["block"] = "clay",},},
	[7] = {[1] = {["pos"] = {7,1},["block"] = "cheapwallpaper",},[2] = {["pos"] = {7,2},["block"] = "clay",},[3] = {["pos"] = {7,3},["block"] = "clay",},[4] = {["pos"] = {7,4},["block"] = "clay",},[5] = {["pos"] = {7,5},["block"] = "clay",},[6] = {["pos"] = {7,6},["block"] = "clay",},[7] = {["pos"] = {7,7},["block"] = "clay",},[8] = {["pos"] = {7,8},["block"] = "clay",},[9] = {["pos"] = {7,9},["block"] = "clay",},[10] = {["pos"] = {7,10},["block"] = "clay",},[11] = {["pos"] = {7,11},["block"] = "clay",},[12] = {["pos"] = {7,12},["block"] = "clay",},[13] = {["pos"] = {7,13},["block"] = "pressurisedbeam",},},
	[8] = {[1] = {["pos"] = {8,1},["block"] = "cheapwallpaper",},[2] = {["pos"] = {8,2},["block"] = "clay",},[3] = {["pos"] = {8,3},["block"] = "clay",},[4] = {["pos"] = {8,4},["block"] = "clay",},[5] = {["pos"] = {8,5},["block"] = "clay",},[6] = {["pos"] = {8,6},["block"] = "clay",},[7] = {["pos"] = {8,7},["block"] = "clay",},[8] = {["pos"] = {8,8},["block"] = "clay",},[9] = {["pos"] = {8,9},["block"] = "pressurisedbeam",},[10] = {["pos"] = {8,10},["block"] = "clay",},[11] = {["pos"] = {8,11},["block"] = "clay",},[12] = {["pos"] = {8,12},["block"] = "pressurisedbeam",},},
	[9] = {[2] = {["pos"] = {9,2},["block"] = "pressurisedbeam",},[3] = {["pos"] = {9,3},["block"] = "clay",},[4] = {["pos"] = {9,4},["block"] = "clay",},},
	[10] = {[2] = {["pos"] = {10,2},["block"] = "pressurisedbeam",},},
	["width"] = 10,
	["height"] = 13,
	["paintEnabled"] = true
}
